config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path=>'',
                      :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
                      :controllers=>{:registrations=>'registrations',
                                      :confirmations=>'confirmations',
                                      :omniauth_callbacks => 'omniauth_callbacks'
                      }

  root 'pages#home'
  
  resources :users, only: [:show]
  resources :companies, path: 'entreprises' do
    resources :reviews, only: [:create, :destroy]
  end
  resources :photos
  
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
  
  resources :subscribers, only: [:new, :update, :index]
  
  get '/search' => 'pages#search'
  get '/searchcompany' => 'pages#searchcompany'
  get '/searching' => 'pages#searching'
  
  get '/contact' => 'pages#contact'
  
  get '/politique-de-confidentialite' => 'pages#confidentialite'
  
  get '/faq' => 'pages#faq'
  
  get '/blog' => 'pages#blog'
  
  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]
  
  resources :contacts, only: [:new, :create]

end

app/models/contact.rb
class Contact < MailForm::Base
   attribute :name,     :validate => true
   attribute :email,     :validate => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
   attribute :sujet,     :validate => true
   attribute :message,     :validate => true
    
    def headers 
        {
        :subject => "Formulaire de contact",
        :to => "edgar.bekier@gmail.com",
        :from => %("#{name}" <#{email}>)
        }
    end 
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(params[:contact])
        @contact.request = request
        if @contact.deliver
            flash.now[:error] = nil
        else
            flash.now[:error] = 'Impossible d\'envoyer.'
            render :new
        end
    end
    
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/create.html.erb
<!-- Content
================================================== -->

<!-- Coming Soon Page -->
<div class="coming-soon-page" style="background: image-url(main-search-background-01.jpg) no-repeat;">
	<div class="container">
		<!-- Search -->
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2">
				<img src="/assets/logovitartisan2.png" alt="">

				<h3>Merci de votre message</h3>
				<h3>Vous recevrez une réponse très bientôt</h3>
				

				
			</div>
		</div>
		<!-- Search Section / End -->
	</div>
</div>
<!-- Coming Soon Page / End -->

app/views/contacts/new.html.erb
<!-- Content
================================================== -->

<!-- Map Container -->
<div class="contact-map margin-bottom-60">

	<!-- Google Maps -->
	<div id="singleListingMap-container">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d167998.10803373056!2d2.2069770643680573!3d48.85877410312378!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66e1f06e2b70f%3A0x40b82c3688c9460!2sParis!5e0!3m2!1sfr!2sfr!4v1528494545191" width="1300" height="480" frameborder="0" style="border:0" allowfullscreen></iframe>
		<a href="#" id="streetView">Street View</a>
	</div>
	<!-- Google Maps / End -->

	<!-- Office -->
	<div class="address-box-container">
		<div class="address-container" data-background-image="images/our-office.jpg">
			<div class="office-address">
				<h3>Nos bureaux</h3>
				<ul>
					<li>4 avenue laurent cely</li>
					<li>92600 asnieres sur seine</li>
					<li>Phone (123) 123-456 </li>
				</ul>
			</div>
		</div>
	</div>
	<!-- Office / End -->

</div>
<div class="clearfix"></div>
<!-- Map Container / End -->


<!-- Container / Start -->
<div class="container">

	<div class="row">

		<!-- Contact Details 
		<div class="col-md-4">

			<h4 class="headline margin-bottom-30">Trouvez nous ici</h4>

			
			<div class="sidebar-textbox">
				<p>Collaboratively administrate channels whereas virtual. Objectively seize scalable metrics whereas proactive e-services.</p>

				<ul class="contact-details">
					<li><i class="im im-icon-Phone-2"></i> <strong>Téléphone:</strong> <span>(123) 123-456 </span></li>
					<li><i class="im im-icon-Fax"></i> <strong>Fax:</strong> <span>(123) 123-456 </span></li>
					<li><i class="im im-icon-Globe"></i> <strong>Web:</strong> <span><a href="#">www.example.com</a></span></li>
					<li><i class="im im-icon-Envelope"></i> <strong>E-Mail:</strong> <span><a href="#">office@example.com</a></span></li>
				</ul>
			</div>

		</div>-->

		<!-- Contact Form -->
		<div class="col-md-12">

			<section id="contact">
				<h4 class="headline margin-bottom-35">Contact</h4>

				<div id="contact-message"></div> 

					<%= form_for @contact do |f| %>

    					<div class="row">
    						<div class="col-md-6">
    							<div>
    							    <%= f.text_field :name, required: true, placeholder:"Votre nom" %>
    								<!--<input name="name" type="text" id="name" placeholder="Votre nom" required="required" />-->
    							</div>
    						</div>
    
    						<div class="col-md-6">
    							<div>
    							    <%= f.email_field :email, required: true, placeholder:"Email" %>
    								<!--<input name="email" type="email" id="email" placeholder="Email" pattern="^[A-Za-z0-9](([_\.\-]?[a-zA-Z0-9]+)*)@([A-Za-z0-9]+)(([\.\-]?[a-zA-Z0-9]+)*)\.([A-Za-z]{2,})$" required="required" />-->
    							</div>
    						</div>
    					</div>
    
    					<div>
    					    <%= f.text_field :sujet, required: true, placeholder:"Sujet" %>
    						<!--<input name="subject" type="text" id="subject" placeholder="Sujet" required="required" />-->
    					</div>
    
    					<div>
    					    <%= f.text_area :message, required: true, placeholder:"Message" %>
    						<!--<textarea name="comments" cols="40" rows="3" id="comments" placeholder="Message" spellcheck="true" required="required"></textarea>-->
    					</div>
                        
                        <%= f.submit 'Envoyer', class:'submit button' %>
    					<!--<input type="submit" class="submit button" id="submit" value="Envoyer" />-->

					<% end %>
			</section>
		</div>
		<!-- Contact Form / End -->

	</div>

</div>
<!-- Container / End -->



<!-- Footer
================================================== -->
<div id="footer" class="sticky-footer">
	<!-- Main -->
	<div class="container">
		<div class="row">
			<div class="col-md-5 col-sm-6">
				<img class="footer-logo" src="/assets/logovitartisan2.png" alt="">
				<br><br>
				<p>Annuaire pour les artisans de France qui cherchent à développer leurs clientèles et pour les personnes qui ont besoin du meilleur artisan pour réaliser le meilleur dépannage.</p>
			</div>

			<div class="col-md-4 col-sm-6 ">
				<h4>Liens utiles</h4>
				<ul class="footer-links">
					<li><a href="<%= new_user_session_path %>">Connexion</a></li>
					<li><a href="<%= new_user_registration_path %>">Inscription</a></li>
					<li><a href="<%= politique_de_confidentialite_path %>">Politique de confidentialité</a></li>
				</ul>

				<ul class="footer-links">
					<li><a href="#">FAQ</a></li>
					<li><a href="<%= blog_path %>">Blog</a></li>
					<li><a href="<%= contact_path %>">Contact</a></li>
				</ul>
				<div class="clearfix"></div>
			</div>		

			<div class="col-md-3  col-sm-12">
				<h4>Contactez-nous</h4>
				<div class="text-widget">
				<!--	<span>12345 Little Lonsdale St, Melbourne</span> <br>
					Phone: <span>(123) 123-456 </span><br>-->
					E-Mail:<span> <a href="#">contact@reparee.fr</a> </span><br>
				</div>

				<ul class="social-icons margin-top-20">
					<li><a href="#"><img src="/assets/facebook.png"></a></li>
					<li><a href="#"><img src="/assets/twitter.png"></a></li>
					<li><a href="#"><img src="/assets/google-plus.png"></i></a></li>
				</ul>

			</div>

		</div>
		
		<!-- Copyright -->
		<div class="row">
			<div class="col-md-12">
				<div class="copyrights">© 2018 Reparee. Tous droits réservés.</div>
			</div>
		</div>

	</div>

</div>
<!-- Footer / End -->


<!-- Back To Top Button -->
<div id="backtotop"><a href="#"></a></div>