config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path=>'',
                      :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
                      :controllers=>{:registrations=>'registrations',
                                      :confirmations=>'confirmations',
                                      :omniauth_callbacks => 'omniauth_callbacks'
                      }

  root 'pages#home'
  
  resources :users, only: [:show]
  resources :companies, path: 'entreprises' do
    resources :reviews, only: [:create, :destroy]
  end
  resources :photos
  
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
  
  resources :subscribers, only: [:new, :update, :index]
  
  get '/search' => 'pages#search'
  get '/searchcompany' => 'pages#searchcompany'
  get '/searching' => 'pages#searching'
  
  get '/contact' => 'pages#contact'
  
  get '/politique-de-confidentialite' => 'pages#confidentialite'
  
  get '/faq' => 'pages#faq'
  
  get '/blog' => 'pages#blog'
  
  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]
  
  resources :contacts, only: [:new, :create]

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
    
      before_action :authenticate_user!

  def new

  end

  def update
    token = params[:stripeToken]

    customer = Stripe::Customer.create(
                                   card: token,
                                   plan: 2090,
                                   email: current_user.email
    )

    current_user.subscribed = true
    current_user.stripeid = customer.id
     if current_user.save
       redirect_to root_path
     end

  end
  
  
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= form_tag subscriber_path(1), method: :put do %>


    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="A month's subscription"
            data-amount="5900"
            data-locale="auto"></script><span>59€ par mois</span>
<% end %>

app/views/subscribers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 panel panel-default form-style">
      <div class="panel-body">
        <h2>Final signup step</h2>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>