config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path=>'',
                      :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
                      :controllers=>{:registrations=>'registrations',
                                      :confirmations=>'confirmations',
                                      :omniauth_callbacks => 'omniauth_callbacks'
                      }

  root 'pages#home'
  
  resources :users, only: [:show]
  resources :companies, path: 'entreprises' do
    resources :reviews, only: [:create, :destroy]
  end
  resources :photos
  
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
  
  resources :subscribers, only: [:new, :update, :index]
  
  get '/search' => 'pages#search'
  get '/searchcompany' => 'pages#searchcompany'
  get '/searching' => 'pages#searching'
  
  get '/contact' => 'pages#contact'
  
  get '/politique-de-confidentialite' => 'pages#confidentialite'
  
  get '/faq' => 'pages#faq'
  
  get '/blog' => 'pages#blog'
  
  match "/404" => "errors#error404", via: [:get, :post, :patch, :delete]
  
  resources :contacts, only: [:new, :create]

end

app/views/layouts/_footer.html.erb
<!-- Footer
================================================== -->
<div id="footer" class="sticky-footer">
	<!-- Main -->
	<div class="container">
		<div class="row">
			<div class="col-md-5 col-sm-6">
				<img class="footer-logo" src="/assets/logo.png" alt="">
				<br><br>
				<p>Morbi convallis bibendum urna ut viverra. Maecenas quis consequat libero, a feugiat eros. Nunc ut lacinia tortor morbi ultricies laoreet ullamcorper phasellus semper.</p>
			</div>

			<div class="col-md-4 col-sm-6 ">
				<h4>Helpful Links</h4>
				<ul class="footer-links">
					<li><a href="#">Login</a></li>
					<li><a href="#">Sign Up</a></li>
					<li><a href="#">My Account</a></li>
					<li><a href="#">Add Listing</a></li>
					<li><a href="#">Pricing</a></li>
					<li><a href="#">Privacy Policy</a></li>
				</ul>

				<ul class="footer-links">
					<li><a href="#">FAQ</a></li>
					<li><a href="#">Blog</a></li>
					<li><a href="#">Our Partners</a></li>
					<li><a href="#">How It Works</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
				<div class="clearfix"></div>
			</div>		

			<div class="col-md-3  col-sm-12">
				<h4>Contact Us</h4>
				<div class="text-widget">
					<span>12345 Little Lonsdale St, Melbourne</span> <br>
					Phone: <span>(123) 123-456 </span><br>
					E-Mail:<span> <a href="#">office@example.com</a> </span><br>
				</div>

				<ul class="social-icons margin-top-20">
					<li><a class="facebook" href="#"><i class="icon-facebook"></i></a></li>
					<li><a class="twitter" href="#"><i class="icon-twitter"></i></a></li>
					<li><a class="gplus" href="#"><i class="icon-gplus"></i></a></li>
					<li><a class="vimeo" href="#"><i class="icon-vimeo"></i></a></li>
				</ul>

			</div>

		</div>
		
		<!-- Copyright -->
		<div class="row">
			<div class="col-md-12">
				<div class="copyrights">© 2017 Listeo. All Rights Reserved.</div>
			</div>
		</div>

	</div>

</div>
<!-- Footer / End -->

app/views/layouts/_navigation.html.erb
 
 <!-- Static navbar -->
 
 <header id="header-container">
   
 		<!-- Header -->
	<div id="header">
    <nav class="navbar navbar-default navbar-static-top" style="margin-bottom:0px; border:0px;">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to image_tag('/assets/logovitartisan2.png'), root_path %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          
          <ul class="nav navbar-nav">
          	<li>
          		<%= link_to 'Service', root_path %>
          	</li>
          	<li>
          	  <a href="<%= faq_path %>">FAQ</a>
          	</li>
          	<li>
          	  <a href="<%= blog_path %>">Blog</a>
          	</li>
          	<li>
          		<%= link_to 'Contact', new_contact_path %>
          	</li>
          </ul>
          
          
          <ul class="nav navbar-nav navbar-right">
            
            <li>
              <a href="<%= new_company_path %>" class="button border with-icon">Ajouter artisan <i class="fas fa-plus"></i></a>
            </li>
            
            <li>
              <%= link_to conversations_path do %>
                Messages
              <% end %>
            </li>
            
            <% if (!user_signed_in?) %>
              <li><%= link_to 'Inscription', new_user_registration_path %></li>
              <li><%= link_to 'Connexion', new_user_session_path %></li>
            <% else %>
            
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= image_tag avatar_url(current_user), class:"img-circle avatar-small" %> <%= current_user.fullname %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Mes annonces", companies_path %></li>
                <li><%= link_to 'Mon profil', user_path(current_user.id) %></li>
                <li><%= link_to 'Modifier mon profil', edit_user_registration_path %></li>
                
                
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Deconnexion', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    </div>
    </header>
<div class="clearfix"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reparee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <!-- CSS
================================================== -->
<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="css/colors/main.css" id="colors">
  
  <%= favicon_link_tag 'favicon.ico' %>
  
</head>
<body>
<%= render 'layouts/navigation' %>

<%= render 'shared/message' %>

<%= yield %>

</body>
<script>



/*----------------------------------------------------*/
	/*  Sticky Header
	/*----------------------------------------------------*/
	$( "#header" ).not( "#header.not-sticky" ).clone(true).addClass('cloned unsticky').insertAfter( "#header" );
	$( "#navigation.style-2" ).clone(true).addClass('cloned unsticky').insertAfter( "#navigation.style-2" );

	// Logo for header style 2
	$( "#logo .sticky-logo" ).clone(true).prependTo("#navigation.style-2.cloned ul#responsive");


	// sticky header script
	var headerOffset = $("#header-container").height() * 2; // height on which the sticky header will shows

	$(window).scroll(function(){
		if($(window).scrollTop() >= headerOffset){
			$("#header.cloned").addClass('sticky').removeClass("unsticky");
			$("#navigation.style-2.cloned").addClass('sticky').removeClass("unsticky");
		} else {
			$("#header.cloned").addClass('unsticky').removeClass("sticky");
			$("#navigation.style-2.cloned").addClass('unsticky').removeClass("sticky");
		}
	});


	/*----------------------------------------------------*/
	/*  Back to Top
	/*----------------------------------------------------*/
	var pxShow = 600; // height on which the button will show
	var scrollSpeed = 500; // how slow / fast you want the button to scroll to top.

	$(window).scroll(function(){
	 if($(window).scrollTop() >= pxShow){
		$("#backtotop").addClass('visible');
	 } else {
		$("#backtotop").removeClass('visible');
	 }
	});

	$('#backtotop a').on('click', function(){
	 $('html, body').animate({scrollTop:0}, scrollSpeed);
	 return false;
	});
</script>
</html>